const sender=document.querySelector('#sender'),subject=document.querySelector('#subject'),message=document.querySelector('#message'),summary=document.querySelector('#summary'),findingsEl=document.querySelector('#findings');let report='';
function inspect(){
 const raw=[sender.value,subject.value,message.value].join(' ').trim();if(!raw){summary.textContent='Paste a message or sender first.';return;}
 const text=raw.toLowerCase(),findings=[];const add=(title,points,detail)=>findings.push({title,points,detail});
 const checks=[
 {pattern:/\b(urgent|immediately|act now|final warning|suspended|verify now|within \d+ hours)\b/i,title:'Time pressure',points:18,detail:'Urgency can discourage careful checking. Verify time-sensitive requests using a contact method you already trust.'},
 {pattern:/\b(password|security code|verification code|ssn|social security|verify your account|confirm your account)\b/i,title:'Sensitive information request',points:24,detail:'Account credentials or identity details are mentioned. Check whether the request is expected and appropriate.'},
 {pattern:/\b(wire transfer|gift cards?|bank account|crypto|bitcoin|prize|winner|payment failed)\b/i,title:'Money or reward language',points:16,detail:'Payment or reward language can be used to pressure recipients. Confirm the context independently.'},
 {pattern:/\.(exe|scr|bat|cmd)\b|\benable (macros|content)\b/i,title:'Executable or macro instructions',points:25,detail:'The text mentions executable attachments or enabling active content. Treat unexpected requests with care.'},
 {pattern:/\b(dear customer|dear user|valued customer)\b/i,title:'Generic greeting',points:5,detail:'A generic greeting is a weak signal by itself. Consider it alongside the sender and requested action.'}
 ];
 checks.forEach(c=>{if(c.pattern.test(text))add(c.title,c.points,c.detail);});
 const urls=[...new Set(raw.match(/https?:\/\/[^\s<>"']+|www\.[^\s<>"']+/gi)||[])];
 const shortened=new Set(['bit.ly','tinyurl.com','t.co','goo.gl','ow.ly','is.gd','buff.ly']);
 const urlHosts=[];
 for(const rawUrl of urls){try{const u=new URL((rawUrl.startsWith('www.')?'https://':'')+rawUrl.replace(/[.,;!?)]*$/,''));urlHosts.push(u.hostname);if(shortened.has(u.hostname.toLowerCase()))add('Shortened destination',12,`${u.hostname} hides the final destination. This tool does not follow the redirect.`);if(u.protocol==='http:')add('Unencrypted link',8,`${u.hostname} uses HTTP. Don't submit sensitive information over this connection.`);if(u.username||u.password)add('User information inside a URL',20,`The actual destination is ${u.hostname}; text before the @ sign is not the host.`);if(/^(\d{1,3}\.){3}\d{1,3}$/.test(u.hostname))add('Numeric destination',12,`The link uses the IP address ${u.hostname} instead of a domain name.`);if(u.hostname.includes('xn--'))add('Encoded international domain',8,`${u.hostname} contains an internationalized label. Check the intended spelling; this is not automatically malicious.`);}catch{add('Unparseable link',5,'A URL could not be parsed. Inspect the complete address manually.');}}
 if(/paypai|micros0ft|arnazon/i.test(sender.value))add('Possible lookalike spelling',20,'The sender contains a spelling that resembles a known brand with substituted characters. Compare it to the verified address.');
 const score=Math.min(100,findings.reduce((n,f)=>n+f.points,0));const label=score>=50?'Multiple warning signs':score>0?'Some warning signs':'No patterns detected';
 document.querySelector('#risk-number').textContent=`${score}/100`;document.querySelector('#risk-label').textContent=label;document.querySelector('#link-count').textContent=urls.length;document.querySelector('#finding-count').textContent=findings.length;document.querySelector('#words').textContent=message.value.trim()?message.value.trim().split(/\s+/).length:0;
 summary.textContent=score>=50?'Several signals deserve a closer look. Verify the request through a known, independent channel.':score?'Review the evidence below. The surrounding context matters.':'No configured warning patterns matched. This does not verify the sender or guarantee the message is safe.';
 findingsEl.replaceChildren();for(const f of findings){const card=document.createElement('article');card.className='finding';const h=document.createElement('h3');h.textContent=f.title;const weight=document.createElement('span');weight.textContent=`+${f.points} points`;h.append(weight);const p=document.createElement('p');p.textContent=f.detail;card.append(h,p);findingsEl.append(card);}
 const p=document.createElement('p');p.className='panel-note';p.textContent=urlHosts.length?`Domains found: ${[...new Set(urlHosts)].join(', ')}. Links were not opened.`:'No web links found in the text.';findingsEl.append(p);
 report=`Phishing inspector\nPattern score: ${score}/100 — ${label}\n${summary.textContent}\n\n${findings.map(f=>`${f.title} (+${f.points}): ${f.detail}`).join('\n')}\n${p.textContent}\n\nHeuristic checks only; not a safety verdict.`;document.querySelector('#copy').disabled=false;document.querySelector('#copy-status').textContent='';
}
document.querySelector('#inspect').addEventListener('click',inspect);document.querySelector('#sample').addEventListener('click',()=>{sender.value='support@paypaI-security.example';subject.value='Urgent: verify your account';message.value='Dear customer, your account will be suspended. Confirm your password immediately at http://192.0.2.1/verify to avoid losing access.';inspect();});
document.querySelector('#clear').addEventListener('click',()=>{sender.value='';subject.value='';message.value='';report='';document.querySelector('#risk-number').textContent='—';document.querySelector('#risk-label').textContent='Ready to inspect';summary.textContent='Add a message to see which warning signs appear.';for(const id of ['link-count','finding-count','words'])document.getElementById(id).textContent='0';findingsEl.replaceChildren();const p=document.createElement('p');p.className='empty-state';p.textContent='Your inspection notes will appear here.';findingsEl.append(p);document.querySelector('#copy').disabled=true;document.querySelector('#copy-status').textContent='';});
document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(report);document.querySelector('#copy-status').textContent='Report copied.';}catch{document.querySelector('#copy-status').textContent='Clipboard unavailable. Select and copy the findings above.';}});
