const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),overlay=document.querySelector('#overlay'),pauseButton=document.querySelector('#pause'),difficulty=document.querySelector('#difficulty'),status=document.querySelector('#game-status');
const size=24,cell=20,speeds={chill:180,classic:125,fast:85};
let snake=[],food,heading={x:1,y:0},queue=[],score=0,timer,running=false,paused=false,best=0;
function readBest(){try{best=Number(localStorage.getItem(`yh-snake-${difficulty.value}`))||0;}catch{best=0;}document.querySelector('#high-score').textContent=best;}
function spawnFood(){const free=[];for(let y=0;y<size;y++)for(let x=0;x<size;x++)if(!snake.some(s=>s.x===x&&s.y===y))free.push({x,y});if(!free.length)return false;food=free[Math.floor(Math.random()*free.length)];return true;}
function draw(){ctx.fillStyle='#120f14';ctx.fillRect(0,0,480,480);ctx.strokeStyle='#241b25';ctx.lineWidth=.5;for(let i=0;i<=24;i++){ctx.beginPath();ctx.moveTo(i*cell,0);ctx.lineTo(i*cell,480);ctx.stroke();ctx.beginPath();ctx.moveTo(0,i*cell);ctx.lineTo(480,i*cell);ctx.stroke();}if(food){ctx.fillStyle='#ff6268';ctx.shadowColor='#ff6268';ctx.shadowBlur=15;ctx.fillRect(food.x*cell+5,food.y*cell+5,10,10);ctx.shadowBlur=0;}snake.forEach((part,i)=>{ctx.fillStyle=i===0?'#ffe5ed':`hsl(344 50% ${Math.max(30,62-i*.8)}%)`;ctx.beginPath();ctx.roundRect(part.x*cell+2,part.y*cell+2,16,16,4);ctx.fill();});}
function reset(){clearTimeout(timer);snake=[{x:12,y:12},{x:11,y:12},{x:10,y:12}];heading={x:1,y:0};queue=[];score=0;paused=false;running=false;spawnFood();readBest();document.querySelector('#score').textContent='0';document.querySelector('#speed').textContent='1×';draw();}
function show(title,copy,button){overlay.hidden=false;document.querySelector('#overlay-title').textContent=title;document.querySelector('#overlay-copy').textContent=copy;document.querySelector('#play').textContent=button;}
function start(){reset();running=true;overlay.hidden=true;pauseButton.disabled=false;pauseButton.textContent='Pause';difficulty.disabled=true;status.textContent='Game on.';canvas.focus({preventScroll:true});schedule();}
function schedule(){clearTimeout(timer);if(running&&!paused)timer=setTimeout(tick,Math.max(45,speeds[difficulty.value]-score*3));}
function finish(won=false){running=false;clearTimeout(timer);difficulty.disabled=false;pauseButton.disabled=true;show(won?'Board complete.':'That’s a wrap.',`${score} bites. ${score===best&&score>0?'A personal best.':'Ready for another round?'}`,'Play again →');status.textContent=won?'You filled the board!':`Game over. Score: ${score}.`;}
function tick(){if(queue.length)heading=queue.shift();const head={x:snake[0].x+heading.x,y:snake[0].y+heading.y};const eating=head.x===food.x&&head.y===food.y;const body=eating?snake:snake.slice(0,-1);if(head.x<0||head.y<0||head.x>=size||head.y>=size||body.some(p=>p.x===head.x&&p.y===head.y)){finish();return;}snake.unshift(head);if(eating){score++;if(score>best){best=score;try{localStorage.setItem(`yh-snake-${difficulty.value}`,String(best));}catch{}}document.querySelector('#score').textContent=score;document.querySelector('#high-score').textContent=best;document.querySelector('#speed').textContent=`${(speeds[difficulty.value]/Math.max(45,speeds[difficulty.value]-score*3)).toFixed(1)}×`;if(!spawnFood()){food=null;draw();finish(true);return;}}else snake.pop();draw();schedule();}
function turn(name){if(!running||paused||queue.length>=2)return;const direction={up:{x:0,y:-1},down:{x:0,y:1},left:{x:-1,y:0},right:{x:1,y:0}}[name];const previous=queue.at(-1)||heading;if(direction.x===-previous.x&&direction.y===-previous.y)return;if(direction.x===previous.x&&direction.y===previous.y)return;queue.push(direction);}
function pause(){if(!running)return;paused=!paused;pauseButton.textContent=paused?'Resume':'Pause';if(paused){clearTimeout(timer);show('Take a breath.','Your game is paused.','Resume →');status.textContent='Paused.';}else{overlay.hidden=true;status.textContent='Game resumed.';canvas.focus({preventScroll:true});schedule();}}
document.querySelector('#play').addEventListener('click',()=>paused?pause():start());pauseButton.addEventListener('click',pause);document.querySelector('#restart').addEventListener('click',start);difficulty.addEventListener('change',()=>{reset();show('Stay hungry.','Press Play to begin.','Play Snake →');});
document.querySelectorAll('[data-direction]').forEach(b=>b.addEventListener('click',()=>turn(b.dataset.direction)));
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName))return;const keys={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',w:'up',a:'left',s:'down',d:'right'};if(keys[e.key]&&running){e.preventDefault();turn(keys[e.key]);}if(e.code==='Space'&&running){e.preventDefault();if(!e.repeat)pause();}});
let touch;canvas.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;touch=null;if(Math.max(Math.abs(dx),Math.abs(dy))<12)return;turn(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');});canvas.addEventListener('pointercancel',()=>touch=null);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running&&!paused)pause();});reset();
